version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"   # or "3.10" / "3.12"; avoid 3.13 if you can

sphinx:
  configuration: docs/conf.py

# Optional: if you add a requirements file later, then:
# python:
#   install:
#     - requirements: docs/requirements.txt
